resource_map:
  # host: resourcemap.instedd.org
  host: resmap-stg.instedd.org
  # host: localhost:3000
  username: bcardiff@manas.com.ar
  password: bcardiff
google_api_key: AIzaSyBwm_YM5joj7fmy0u9HqDMWi2j2lUAArGs
